### ISSUE TITLE
과제 피드백

### ISSUE THREAD

**Issue by DongHyunKIM-Hi** [guswlsdl0121/reboot-review-service#3]
- 프로젝트 잘 봤습니다! 파사드 패턴 비슷하게 분리해서 관리한 점도 흥미로웠습니다.
- 또한 @Retryable 어노테이션 사용해서 문제 해결한 부분도 인상적이네요.
- 다만 코드에 대해서 주석을 달아주는 것이 좀 더 코드의 가독성을 높이는데 도움이 될 것같습니다.
- 예를들어 productRepositroy 코드가 주석 처리가 되어 있는데 이거 왜 주석 처리 되었는지 알아야 같이 일할 때 불필요한 문제가 발생하지 않을 수 있기 때문입니다.
- 커밋 메시지는 꼼꼼하게 잘 작성해주셔서 좋았습니다. 컨밴션도 지키려고 하셨구요.
- 이건 취향일 수 도 있겠지만 개인적으로는 spring mvc 패턴을 볼 때 어느정도 흐름이 예상되어야 한다고 생각합니다. 어떤 도메인의 어떤 기능을 사용하려면 일단 해당 도메인의 service 파일에 접근해서 가져가야 한다든지 이런 것이 지켜지면 현재 코드 뿐만 아니라 일할 때 좀 더 코드 파악이 쉬울 것 같아요. 만약 팀에 서비스가 50개의 프로젝트가 있다고 할 경우에 패턴이 다 다르면 코드를 유지보수하기에 힘들 것 같다는 의견입니다.

**Comment by guswlsdl0121** [comment]
아하.. 이번 과제에서 피드백 반영해서 개선하겠습니다. 감사합니다!
